version: 2
jobs:

  ##############################################################################################################
  ##############################################################################################################

  build:
    docker:
    - image: circleci/android:api-28-alpha
    working_directory: ~/workspace

    steps:
    - checkout

    - run:
        name: Chmod permissions #if exec permission missing
        command: |
          sudo chmod +x ./gradlew
          sudo chmod +x .circleci/android-wait-for-boot.sh

    - restore_cache:
        key: v1-jars-{{ checksum "build.gradle" }}

    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - run:
        name: Download temp Retrofit adjustements
        command: |
          wget https://github.com/nenick/retrofit/releases/download/2.5.1-coroutines/retrofit-2.5.1-coroutines.jar -P data-network/libs/

    - run:
        name: Build debug APK and test APK
        command: |
          ./gradlew app:assembleDebug
          ./gradlew app:assembleDebugAndroidTest

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-jars-{{ checksum "build.gradle" }}

    # cache workspace to share build artifacts with next steps
    - save_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - ~/workspace

  ##############################################################################################################
  ##############################################################################################################

  app-unit-tests:
    docker:
    - image: circleci/android:api-28-alpha
    working_directory: ~/workspace

    steps:
    # get cached build artifacts and dependencies
    - restore_cache:
        keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - v1-jars-{{ checksum "build.gradle" }}

    - run:
        name: Unit tests
        command: ./gradlew app:testDebugUnitTest

    - run:
        name: Code coverage
        command: ./gradlew app:jacocoUnitTestReport

    - run:
        name: Lint checks
        command: ./gradlew app:lintDebug

    # store test result for CircleCi to show test statistics
    - store_test_results:
        path: app/build/test-results/testDebugUnitTest

    # store test result to watch it later
    - store_artifacts:
        path: app/build/reports/tests/testDebugUnitTest
        destination: unit-tests

    # store test coverage to watch it later
    - store_artifacts:
        path: app/build/reports/jacoco/jacocoUnitTestReport/html
        destination: unit-tests-coverage

    # store lint report to watch it later
    - store_artifacts:
        path: app/build/reports/lint-results-debug.html
        destination: lint-checks/lint-results-debug.html

    # cache unit test coverage to share it with next build steps
    - save_cache:
        key: v1-app-unit-test-coverage-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - app/build/jacoco

  ##############################################################################################################
  ##############################################################################################################

  data-local-unit-tests:
    docker:
    - image: circleci/android:api-28-alpha
    working_directory: ~/workspace

    steps:
    # get cached build artifacts and dependencies
    - restore_cache:
        keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - v1-jars-{{ checksum "build.gradle" }}

    - run:
        name: Unit tests
        command: ./gradlew data-local:testDebugUnitTest

    - run:
        name: Code coverage
        command: ./gradlew data-local:jacocoUnitTestReport

    - run:
        name: Lint checks
        command: ./gradlew data-local:lintDebug

    # store test result for CircleCi to show test statistics
    - store_test_results:
        path: data-local/build/test-results/testDebugUnitTest

    # store test result to watch it later
    - store_artifacts:
        path: data-local/build/reports/tests/testDebugUnitTest
        destination: unit-tests

    # store test coverage to watch it later
    - store_artifacts:
        path: data-local/build/reports/jacoco/jacocoUnitTestReport/html
        destination: unit-tests-coverage

    # store lint report to watch it later
    - store_artifacts:
        path: data-local/build/reports/lint-results-debug.html
        destination: lint-checks/lint-results-debug.html

    # cache unit test coverage to share it with next build steps
    - save_cache:
        key: v1-data-local-unit-test-coverage-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - data-local/build/jacoco

  ##############################################################################################################
  ##############################################################################################################

  data-network-unit-tests:
    docker:
    - image: circleci/android:api-28-alpha
    working_directory: ~/workspace

    steps:
    # get cached build artifacts and dependencies
    - restore_cache:
        keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - v1-jars-{{ checksum "build.gradle" }}

    - run:
        name: Unit tests
        command: ./gradlew data-network:testDebugUnitTest

    - run:
        name: Code coverage
        command: ./gradlew data-network:jacocoUnitTestReport

    - run:
        name: Lint checks
        command: ./gradlew data-network:lintDebug

    # store test result for CircleCi to show test statistics
    - store_test_results:
        path: data-network/build/test-results/testDebugUnitTest

    # store test result to watch it later
    - store_artifacts:
        path: data-network/build/reports/tests/testDebugUnitTest
        destination: unit-tests

    # store test coverage to watch it later
    - store_artifacts:
        path: data-network/build/reports/jacoco/jacocoUnitTestReport/html
        destination: unit-tests-coverage

    # store lint report to watch it later
    - store_artifacts:
        path: data-network/build/reports/lint-results-debug.html
        destination: lint-checks/lint-results-debug.html

    # cache unit test coverage to share it with next build steps
    - save_cache:
        key: v1-data-network-unit-test-coverage-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - data-network/build/jacoco

  ##############################################################################################################
  ##############################################################################################################

  app-android-tests:
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      _JAVA_OPTIONS: -Xmx3200m

    working_directory: /home/circleci/workspace

    steps:
    # get cached build artifacts and dependencies
    - restore_cache:
        keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - v1-jars-{{ checksum "build.gradle" }}

    - run:
        name: Store Google Service Account
        command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - run:
        name: Authorize gcloud and set config defaults
        command: |
          sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
    - run:
        name: Test with Firebase Test Lab
        command: >
          sudo gcloud firebase test android run \
            --type instrumentation \
            --app app/build/outputs/apk/debug/app-debug.apk \
            --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=Pixel2,version=28,locale=en,orientation=portrait \
            --environment-variables coverage=true,coverageFile=/sdcard/tmp/code-coverage/connected/coverage.ec \
            --directories-to-pull=/sdcard/tmp
    - run:
        name: Install gsutil dependency and copy test results data
        command: |
          sudo pip install -U crcmod
          sudo gsutil -m cp -r -U `sudo gsutil ls gs://${GOOGLE_TESTLAB_RESULTS} | tail -1` ${CIRCLE_ARTIFACTS}/ | true

        #TODO add app-tests run

    - run:
        name: Code coverage
        command: |
          ./gradlew app:jacocoInstrumentationTestReport
          ./gradlew app-tests:jacocoInstrumentationTestReport

    - store_artifacts:
        path: app/build/reports/androidTests/connected
        destination: app/instrumentation-tests
    - store_artifacts:
        path: app/build/reports/jacoco/jacocoInstrumentationTestReport/html
        destination: app/instrumentation-tests-coverage
    - store_artifacts:
        path: app/build/reports/lint-results-debug.html
        destination: app/lint-checks/lint-results-debug.html
    - store_test_results:
        path: app/build/outputs/androidTest-results/connected

    - store_artifacts:
        path: app-tests/build/reports/androidTests/connected
        destination: app-tests/instrumentation-tests
    - store_artifacts:
        path: app-tests/build/reports/jacoco/jacocoInstrumentationTestReport/html
        destination: app-tests/instrumentation-tests-coverage
    - store_test_results:
        path: app-tests/build/outputs/androidTest-results/connected

    # cache test coverage to share it with next build steps
    - save_cache:
        key: v1-app-android-test-coverage-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - app/build/outputs/code-coverage/connected
        - app-tests/build/outputs/code-coverage/connected

  ##############################################################################################################
  ##############################################################################################################

  test-coverage-report:
    docker:
    - image: circleci/android:api-28-alpha
    working_directory: ~/workspace

    steps:
    # get cached build artifacts and dependencies
    - restore_cache:
        keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - v1-jars-{{ checksum "build.gradle" }}
        - v1-app-unit-test-coverage-{{ .Environment.CIRCLE_SHA1 }}
        - v1-app-android-test-coverage-{{ .Environment.CIRCLE_SHA1 }}
        - v1-dats-local-unit-test-coverage-{{ .Environment.CIRCLE_SHA1 }}
        - v1-data-remote-unit-test-coverage-{{ .Environment.CIRCLE_SHA1 }}

    - run:
        name: Code coverage
        command: |
          ./gradlew jacocoMergedTestReport

    - run:
        name: Code coverage report at codacy
        command: |
          wget https://github.com/nenick/codacy-coverage-reporter/releases/download/4.1.0-alpha/codacy-coverage-reporter-assembly-4.1.0-alpha.jar
          java -jar codacy-coverage-reporter-assembly-4.1.0-alpha.jar report -l Kotlin -r build/reports/jacoco/jacocoMergedTestReport/jacocoMergedTestReport.xml --multi-module app/src/main/java,data-local/src/main/java,data-network/src/main/java

    - store_artifacts:
        path: build/reports/jacoco/jacocoMergedTestReport/html
        destination: merged-tests-coverage


  ##############################################################################################################
  ##############################################################################################################

workflows:
  version: 2
  build-and-test:
    jobs:
    - build
    - app-unit-tests:
        requires:
        - build
    - data-local-unit-tests:
        requires:
        - build
    - data-network-unit-tests:
        requires:
        - build
    - app-android-tests:
        requires:
        - build
    - test-coverage-report:
        requires:
        - app-unit-tests
        - data-local-unit-tests
        - data-network-unit-tests
        - app-android-tests