version: 2
jobs:
  build:
    docker:
      - image: bitriseio/docker-android:v2018_11_11-10_19-b1334

    working_directory: ~/workspace

    steps:
      - run:
          name: Create avd
          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-25;default;armeabi-v7a"
          environment:
            TERM: dumb

      - run:
          name: Start emulator
          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window
          background: true
          environment:
            TERM: dumb

      - checkout

      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Build debug APK and test APK
          command: |
            ./gradlew app:assembleDebug
            ./gradlew app:assembleDebugAndroidTest

      - run:
          name: Unit tests
          command: |
            ./gradlew app:testDebugUnitTest
            ./gradlew data-local:testDebugUnitTest
            ./gradlew data-network:testDebugUnitTest

      - run:
          name: Coverage report
          command: |
            ./gradlew data-network:jacocoUnitTestReport

      - run:
          name: Wait for emulator
          command: ./android-wait-for-boot.sh
          environment:
            TERM: dumb

      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb

      - run:
          name: Instrumentation testing
          command: ./gradlew app:connectedCheck
          environment:
            TERM: dumb