version: 2
jobs:
  build:
    docker:
      - image: bitriseio/docker-android:v2018_11_11-10_19-b1334

    working_directory: ~/workspace

    steps:
      - checkout

      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Build debug APK and test APK
          command: |
            ./gradlew app:assembleDebug
            ./gradlew app:assembleDebugAndroidTest

      - run:
          name: Unit tests
          command: |
            ./gradlew app:testDebugUnitTest
            ./gradlew data-local:testDebugUnitTest
            ./gradlew data-network:testDebugUnitTest

      - run:
          name: Coverage report
          command: |
            ./gradlew data-network:jacocoUnitTestReport
