version: 2
jobs:
  build:
    docker:
      - image: bitriseio/docker-android:v2018_11_11-10_19-b1334
    environment:
      JVM_OPTS: -Xmx3200m

    working_directory: ~/workspace

    steps:
      - checkout

      - run:
         name: Chmod permissions #if exec permission missing
         command: |
           sudo chmod +x ./gradlew
           sudo chmod +x .circleci/android-wait-for-boot.sh

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Build debug APK and test APK
          command: |
            ./gradlew app:assembleDebug
            ./gradlew app:assembleDebugAndroidTest

      - run:
          name: Unit tests
          command: |
            ./gradlew app:testDebugUnitTest
            ./gradlew data-network:testDebugUnitTest
            ./gradlew data-local:testDebugUnitTest

      - run:
          name: Lint checks
          command: |
            ./gradlew app:lintDebug
            ./gradlew data-local:lintDebug
            ./gradlew data-network:lintDebug

      - run:
          name: Create emulator
          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-24;default;armeabi-v7a"
          environment:
            TERM: dumb

      - run:
          name: Start emulator
          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window
          background: true
          environment:
            TERM: dumb

      - run:
          name: Wait for emulator
          command: .circleci/android-wait-for-boot.sh
          environment:
            TERM: dumb

      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb

      - run:
          name: Instrumentation testing
          command: |
            ./gradlew app:connectedCheck
            ./gradlew app-tests:connectedCheck
          environment:
            TERM: dumb

      - run:
          name: Code coverage
          command: |
            ./gradlew app:jacocoUnitTestReport
            ./gradlew app:jacocoInstrumentationTestReport
            ./gradlew app-tests:jacocoInstrumentationTestReport
            ./gradlew data-local:jacocoUnitTestReport
            ./gradlew data-network:jacocoUnitTestReport
            ./gradlew jacocoMergedTestReport

      - run:
          name: Code coverage report at codacy
          command: |
            wget https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.5/codacy-coverage-reporter-4.0.5-assembly.jar
            java -jar codacy-coverage-reporter-4.0.5-assembly.jar report -l Java -r app/build/reports/jacoco/jacocoInstrumentationTestReport/jacocoInstrumentationTestReport.xml --partial
            java -jar codacy-coverage-reporter-4.0.5-assembly.jar report -l Java -r data-local/build/reports/jacoco/jacocoUnitTestReport/jacocoUnitTestReport.xml --partial
            java -jar codacy-coverage-reporter-4.0.5-assembly.jar final

      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: app/unit-tests
      - store_artifacts:
          path: app/build/reports/jacoco/jacocoUnitTestReport
          destination: app/unit-tests-coverage
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: app/build/reports/androidTests/connected
          destination: app/instrumentation-tests
      - store_artifacts:
          path: app/build/reports/jacoco/jacocoInstrumentationTestReport/html
          destination: app/instrumentation-tests-coverage
      - store_artifacts:
          path: app/build/reports/lint-results-debug.html
          destination: app/lint-checks/lint-results-debug.html
      - store_test_results:
          path: app/build/outputs/androidTest-results/connected

      - store_artifacts:
          path: app-tests/build/reports/androidTests/connected
          destination: app-tests/instrumentation-tests
      - store_artifacts:
          path: app-tests/build/reports/jacoco/jacocoInstrumentationTestReport/html
          destination: app-tests/instrumentation-tests-coverage
      - store_test_results:
          path: app-tests/build/outputs/androidTest-results/connected

      - store_artifacts:
          path: data-local/build/reports/tests/testDebugUnitTest
          destination: data-local/unit-tests
      - store_artifacts:
          path: data-local/build/reports/jacoco/jacocoUnitTestReport
          destination: data-local/unit-tests-coverage
      - store_artifacts:
          path: data-local/build/reports/lint-results-debug.html
          destination: data-local/lint-checks/lint-results-debug.html
      - store_test_results:
          path: data-local/build/test-results/testDebugUnitTest

      - store_artifacts:
          path: data-network/build/reports/tests/testDebugUnitTest
          destination: data-network/unit-tests
      - store_artifacts:
          path: data-network/build/reports/jacoco/jacocoUnitTestReport
          destination: data-network/unit-tests-coverage
      - store_artifacts:
          path: data-network/build/reports/lint-results-debug.html
          destination: data-network/lint-checks/lint-results-debug.html
      - store_test_results:
          path: data-network/build/test-results/testDebugUnitTest

      - store_artifacts:
          path: build/reports/jacoco/jacocoMergedTestReport/html
          destination: merged-tests-coverage