parameters:
  - name: 'modules'
    type: object

steps:
  - script: |
    echo "${{parameters.modules}}"
    echo "${{join(' ', parameters.modules)}}"
  - task: Bash@3
    displayName: Moule list check
    inputs:
      filePath: 'pipelines/tasks/check-module-list.sh'
      arguments: ${{join(' ', parameters.modules)}}
    condition: succeededOrFailed()