parameters:
  - name: 'modules'
    type: object

steps:
  - ${{each module in parameters.modules}}:
    - task: PublishPipelineArtifact@1
      displayName: Report ${{module}}
      inputs:
        targetPath: '${{module}}/build/reports'
        artifactName: "reports-${{replace(module, '/', '-')}}"
      condition: succeededOrFailed()