parameters:
  - name: 'modules'
    type: object

steps:
  - task: Gradle@2
    displayName: Create Coverage Report
    inputs:
      tasks: 'jacocoTestReportMerge'
      options: '-PcoverageSkipTestTasks'
      gradleWrapperFile: 'gradlew'
      publishJUnitResults: false
    condition: succeededOrFailed()

  - bash: mkdir -p build/coverage/sources
    displayName: Collection directory
    condition: succeededOrFailed()

  - ${{each module in parameters.modules}}:
      - bash: cp -r ${{module}}/src/*/java/* build/coverage/sources
        displayName: Collect sources ${{module}}
        condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: Report Coverage
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: 'build/reports/jacoco/merged/jacocoTestReport.xml'
      pathToSources: 'build/coverage/sources'
      failIfCoverageEmpty: true
    condition: succeededOrFailed()