parameters:
  - name: 'modules'
    type: object
  - name: 'prefix'
    type: string

steps:
  - ${{each module in parameters.modules}}:
    - task: PublishPipelineArtifact@1
      displayName: Report ${{module}}
      inputs:
        targetPath: '${{module}}/build/reports'
        artifactName: "${{prefix}}reports-${{replace(module, '/', '-')}}"
      condition: succeededOrFailed()