parameters:
  - name: 'modules'
    type: object
    default:
      - app
      - tools/wiremock-android

schedules:
  - cron: "0 0 * * *"
    displayName: Daily Midnight Build
    branches:
      include:
        - master

jobs:
  - job:
    displayName: Ensure all modules are listed
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - bash: |
          MODULES_EXISTS=$(cat settings.gradle | sed s/"include ':"//g | sed s/\:/\\//g | sed s/\'//g)
          MODULES_LISTED=$( echo ${{join(' ', parameters.modules)}} | sed s/ /\n/g)
          echo ""
          echo "== MODULES_EXISTS =="
          echo "$MODULES_EXISTS"
          echo ""
          echo "== MODULES_LISTED =="
          echo "$MODULES_LISTED"
          echo ""
          if [ "$MODULES_EXISTS" != "$MODULES_LISTED" ] then
            echo "listed modules does not match settings.gradle"
            exit 1
          fi

  - job:
    displayName: Tests and checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/debug-build-and-test.yml

  - job:
    displayName: Static code quality checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: tasks/android-lint.yml
      - template: tasks/kotlin-ktlint.yml
      - template: tasks/publish-reports.yml
        parameters:
          modules: ${{parameters.modules}}

  - job:
    displayName: Project tasks output checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - task: Bash@3
        displayName: Start Emulator
        inputs:
          filePath: 'pipelines/templates/android-emulator.sh'
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Ktlint
        inputs:
          tasks: 'ktlint-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Jacoco
        inputs:
          tasks: 'jacoco-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Clean
        inputs:
          tasks: 'clean-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()