parameters:
  - name: 'param'
    type: object
    default:
      - FOO
      - BAR
      - ZOO

schedules:
  - cron: "0 0 * * *"
    displayName: Daily Midnight Build
    branches:
      include:
        - master

jobs:
  - job:
    displayName: Tests and checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/debug-build-and-test.yml

  - job:
    displayName: Static code quality checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - ${{ each p in parameters.param }}:
        - script: echo ${{ p }}
      - template: templates/ktlint.yml
      - template: templates/publish-reports.yml
        parameters:
          modules: $(parameters.param)

  - job:
    displayName: Project tasks output checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - task: Bash@3
        displayName: Start Emulator
        inputs:
          filePath: 'pipelines/templates/android-emulator.sh'
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Ktlint
        inputs:
          tasks: 'ktlint-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Jacoco
        inputs:
          tasks: 'jacoco-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Clean
        inputs:
          tasks: 'clean-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()