schedules:
  - cron: "0 0 * * *"
    displayName: Daily Midnight Build
    branches:
      include:
        - master

jobs:
  - job:
    displayName: Tests and checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/debug-build-and-test.yml

  - job:
    displayName: Project tasks output check
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - task: Gradle@2
        displayName: Ktlint
        inputs:
          tasks: 'ktlint-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Jacoco
        inputs:
          tasks: 'jacoco-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Clean
        inputs:
          tasks: 'clean-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()