schedules:
  - cron: "0 0 * * *"
    displayName: Daily Midnight Build
    branches:
      include:
        - master

variables:
  modules: ["app", "tools:wiremock-android", "tools:wiremock-kotlindsl"]

jobs:
  - job:
    displayName: Tests and checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/debug-build-and-test.yml

  - job:
    displayName: Static code quality checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/ktlint.yml
        parameters:
          modules: ["app", "tools:wiremock-android"]

  - job:
    displayName: Project tasks output checks
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - task: Bash@3
        displayName: Start Emulator
        inputs:
          filePath: 'pipelines/templates/android-emulator.sh'
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Ktlint
        inputs:
          tasks: 'ktlint-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Jacoco
        inputs:
          tasks: 'jacoco-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()

      - task: Gradle@2
        displayName: Clean
        inputs:
          tasks: 'clean-check'
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: false
        condition: succeededOrFailed()